# Generated by Django 4.1.1 on 2022-09-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_book_note_book_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("url", models.CharField(max_length=255)),
                ("score", models.IntegerField()),
                ("comments", models.IntegerField()),
            ],
        ),
    ]
